# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "farming engineers organic produce"
description: > # this means to ignore newlines until "email:"
   from Pickard to your plate

email: burkefarm@gmail.com
#blog logo
logo: "/assets/images/logo.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/img_7351.jpg"

name: 'farming engineers organic produce'

store_url: 'https://store.farmingengineers.com'

paginate:	5

url: "https://farmingengineers.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
#twitter_handle: '@dirkfabisch'

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon: facebook
    url:  https://www.facebook.com/The-Farming-Engineers-Organic-Produce-136276076392635/
    desc: Like us on Facebook!
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon: instagram
    url:  https://instagram.com/farmingengineers
    desc: Follow us on Instagram!
